spring:
  application:
    name: TAG-Board
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:tag-board-db}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0
  port: ${PORT:8080}


############################
# PostgresSQL config
############################

#spring:
#  application:
#    name: TAG-Board
#  datasource:
#    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5434}/${DB_NAME:tag-board-db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:root}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#
#server:
#  port: ${PORT:8080}